name: babie/self-build
description: build htmls from markdowns

runs:
  using: composite
  steps:
    - name: Checkout self-web
      uses: actions/checkout@v3
      with:
        repository: 'babie/self-web'
        path: ./self-web
        ref: v0
    - name: Copy docs and config
      run: |
        cp -r ./docs/* self-web/src/content/
        cp -f ./self.config.json self-web/
        jq '.site | if endswith(".github.io") then "" else . end' ./self.config.json -r | read site; if [ -z $site ]; then echo "noop"; else echo $site > self-web/public/CNAME; fi
      shell: bash
    - name: Install, Build and Upload
      uses: withastro/action@v0
      with:
          path: ./self-web
          node-version: 16
          package-manager: pnpm
    - name: Deploy
      id: deployment
      uses: actions/deploy-pages@v1
